### ISSUE TITLE
Update Framework to 11.0.x in master

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/GeneralCatalog#2]
As there now is a branch rel-10.1 and master can be used for OTOBO 11

**Comment by stefanhaerter** [comment]
Can this be closed?

**Comment by bschmalhofer** [comment]
Yes, this can be closed. The framework version was updated in the commit  #c5655088305c5bd6099f4e30913a0b097fa178af.

**Comment by bschmalhofer** [comment]
Closing now.
